---
title: "R Notebook"
output: html_notebook
---


```{r}

data("USArrests")
states = row.names(USArrests)
states
names(USArrests)

apply(USArrests, 2, mean)
apply(USArrests, 2, var)
```

```{r}
pr.out = prcomp(USArrests, scale=TRUE)
names(pr.out)

pr.out$center
pr.out$scale
pr.out$rotation

dim(pr.out$x)
biplot(pr.out, scale=0)
pr.out$sdev

pr.var = pr.out$sdev^2
pr.var

pve = pr.var/sum(pr.var)
pve

```

IRIS PCA

```{r}

data("iris")
head(iris)

irisdata1 <- iris[,1:4]
irisdata1

help("princomp")

p_comps <- princomp(irisdata1, cor=TRUE, score=TRUE)
summary(p_comps)

plot(p_comps)
plot(p_comps, type="l")

biplot(p_comps)


```

BOSTON PCA

```{r}
install.packages("MASS")
data(Boston, package="MASS")

help(Boston)
help(prcomp)

pca_out <- prcomp(Boston, scale=TRUE)
pca_out
plot(pca_out)

biplot(pca_out, scale=0)
boston_pc <- pca_out$x
boston_pc
head(boston_pc)
summary(boston_pc)

```












